<head>
<style>
    tr{
        padding:20px;
    }
</style>
</head>
<body>
@include('layouts.app')
<table>
<thead>
    <td><b>Title</b></td>
    <td><b>Description</b></td>
    <td><b>Author</b></td>
    <td><b>Publisher</b></td>
    <td><b>Category</b></td>
    <td><b>Publication</b></td>
</thead>
<tbody>
@foreach($books as $book)
<tr>
    <td>{{$book->title}}</td>
    <td>{{$book->description}}</td>
    <td>{{$book->Fname.' '.$book->Lname}}</td>
    <td>{{$book->publisher}}</td>
    <td>{{$book->category}}</td>
    <td>{{$book->publication}}</td>
</tr>
@endforeach
</tbody>
</table>
</body>
